### ISSUE TITLE
Support for embedded PDB / other types(?

### ISSUE THREAD

**Issue by EvaisaDev** [EvaisaDev/UnityNetcodePatcher#2]
Not sure if possible

**Comment by Lordfirespeed** [comment]
This should deffo be possible, Cecil does have ways of reading the embedded PDB data, but it's a question of whether we would need to edit the Netcode source code I think 😓

**Comment by EvaisaDev** [comment]
> This should deffo be possible, Cecil does have ways of reading the embedded PDB data, but it's a question of whether we would need to edit the Netcode source code I think 😓

Shouldn't, since we are reading the pdb file from our end already.
