### ISSUE TITLE
Adhere to GNU CLI standards

### ISSUE THREAD

**Issue by Lordfirespeed** [EvaisaDev/UnityNetcodePatcher#7]
See here: 

https://www.gnu.org/prep/standards/html_node/Command_002dLine-Interfaces.html#Command_002dLine-Interfaces

Todo: 
- [ ] Implement `--help` / `-h`
- [ ] Implement `--version` / `-v`

The [System.CommandLine](https://learn.microsoft.com/en-us/dotnet/standard/commandline/get-started-tutorial) package could be helpful for achieving this.

**Comment by EvaisaDev** [comment]
I have been attemping to rewrite it using System.CommandLine but cannot get it to work, and i am tired of trying at this point.
dev branch has my attempt.

**Comment by Lordfirespeed** [comment]
I'll have a crack at it
